### ISSUE TITLE
Inconsistencies in JS examples

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2700]
Found while working on #2698

Apart from ES5 consistency (addressed in #2698) there are several other ways where our JS examples are inconsistent:

- some are applied directly to one instance of pattern, other may work with multiple patterns on a page
- some use ids to select elements, other use class names, others aria-* attributes
- some will silently handle case when pattern doesn't exist on the page, others will fail with errors
- some have detailed code comments, others have none
- some are wrapped in self invoking anonymous function, others just define variables and functions in global scope

Now, that we want to surface JS examples in documentation it would be good to fix those inconsistencies.

### TODO

- [ ] update scripts to apply to all instances of given pattern, not just one
- [ ] make sure there are no errors when pattern doesn't exist on the page
- [ ] within a pattern use aria-* attributes to select controls
- [ ] add comments
- [ ] don't wrap in self invoked function for clarity (assume developer will know what to do to fit script into their build system) (?)
