### ISSUE TITLE
Make sure all existing functionality works in Flask

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2758]
- [x] templatefinder markdown makes some HTML tags escaped (because of IDRenderer added in canonical-web-and-design/canonicalwebteam.templatefinder#11)
- [x] Table of contents sidebar doesn't seem to appear. [canonical-web-and-design/canonicalwebteam.templatefinder#9 ]
- [x] some examples have block elements injected by markdown parser [canonical-web-and-design/canonicalwebteam.templatefinder/issues/10]

To verify:
- search/filter
- codepen
- examples
- main navigation

**Comment by bartaz** [comment]
Reported https://github.com/canonical-web-and-design/canonicalwebteam.templatefinder/issues/9 as templatefinder issue to create ids for headings.

**Comment by bartaz** [comment]
Closed by #2807
