### ISSUE TITLE
Finalize merging vanillaframework.io site with docs

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2895]
- [x] update  release drafter template
- [x] update release process wiki page
- [x] update releases.demo.haus
- [x] update search API to search vanillaframework.io/docs instead of docs.vanillaframework.io
- [x] use templates instead of the site for consistency with other projects
- [x] move common parts to includes (<head>, navigation, footer...)
- [x] review head tags of docs/site (GA, lazy loading, usabilla, etc)
- [x] review how much of custom docs/site css is needed
- [ ] implement wider redesign
- [ ] consider what to do with PWA: app-iconsmanifest.json, sw.js (service worker / offline), sitemap
- [x] archive vanillaframework.io repo
