### ISSUE TITLE
[Accessibility] Modal issues

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3223]
### Tabbing

[Example ](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html)

[Example](https://ubuntu.com/core#get-in-touch) on ubuntu.com where you have to cycle through the entire page to bring focus inside the modal window

-  Manage focus with js

- If activating a button opens a dialog, the focus moves inside the dialog.)[Ours](https://vanillaframework.io/docs/examples/patterns/contextual-menu/dark) doesn't)

 Tabbing moves focus outside modal, which shouldn't happen according to  the [requirements](https://www.w3.org/TR/wai-aria-practices/#dialog_modal)

In the screenshot below, the tab focus moved to the switch which is outside the toggle: 

![image](https://user-images.githubusercontent.com/2741678/91324973-93edf400-e7ba-11ea-95df-88cf9a40622d.png)

### Roles, States, and Properties
- The dialog container element must have aria-modal set to true.

## TODO

- [x] Add aria-modal
- [x] Keep focus inside modal
- [x] ESC to close
- [x] Bring focus back to the element that opened the dialog

**Comment by lyubomir-popov** [comment]
For the focus looping part, an [example](https://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html) that seems to do it and a stackoverflow [discussion](https://stackoverflow.com/questions/44452084/how-to-keep-focus-within-modal-dialog) I stumbled on

**Comment by bartaz** [comment]
At least part of it should be already done.
We should verify if anything remains to be implemented.
